name: "Setup Environment"
description: "Create config files and credentials needed to run basedosdados client"
author: "Base dos Dados"
inputs: 
  GCP_BD_DEV_PROD:
    description: Github secret credential
    required: true

  GCP_BD_DEV_STAGING: 
    description: Github secret credential
    required: true

runs: 
  using: composite
  steps:
    - run: pip install --upgrade -r ${{ github.workspace }}\requirements-dev.txt 
      shell: cmd
    - run: python ${{ github.workspace }}\setup.py develop
      shell: cmd
    - run: python  ${{ github.action_path }}\main.py
      shell: cmd
    - run: pytest
      shell: cmd