site_name: Base Dos Dados

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  palette:
    primary: teal
  language: pt
  favicon: https://avatars3.githubusercontent.com/u/71097635?s=400&u=59375d7ae320f43b2bb6accc8ef6dd79837c88f5&v=4

repo_url: https://github.com/base-dos-dados/bases/tree/organize-docs/docs
repo_name: base-dos-dados/bases

extra:
  version: 2.0
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/basedosdados?lang=en
nav:
  - Introduction: index.md

markdown_extensions:
  - codehilite
  - admonition
  - toc:
      permalink: 
  - markdown_include.include:
      base_path: docs