name: data-check

on:
  push:
    paths:
    - bases/**/**.yaml
    - bases/**/**.sql

jobs:
  get_changes:
    runs-on: ubuntu-latest
    steps:

      - name: Create Changes
        id: file_changes
        uses: trilom/file-changes-action@v1.2.4

      - name: Copy Changes
        run: cp $HOME/files.json files.json

      - name: Upload Changes
        uses: actions/upload-artifact@v2
        with:
          name: push-changes
          path: files.json

  data-check:
    needs: get_changes
    runs-on: ubuntu-latest
    env:
      GCP_BD_DEV_PROD: ${{ secrets.ACTION_TEST }}
      GCP_BD_DEV_STAGING: ${{ secrets.ACTION_TEST }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download changes
        uses: actions/download-artifact@v2
        with:
          name: push-changes
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.x'
      - name: Create Environment
        uses: ./.github/workflows/data-check/